resources:
  - name: basic_usage_json_example
    kafka:
      type: simple
      consumer_group_id: basic_usage_group
      topics:
        - user_json_topic
        # - product_json_topic
    processing:
      serializer: json
      target_dataset: json_sources
      batch_size: 1000
      batch_timeout: 5
  
  - name: basic_avro_example
    kafka:
      type: simple
      consumer_group_id: avro_usage_group
      topics_regex: ".*_avro_topic$"
    processing:
      serializer: avro
      target_dataset: dlt_kafka_ecommerce
      batch_size: 1000
      batch_timeout: 5